# Generated by Django 4.1 on 2022-09-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_birth_date_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='work_at',
            field=models.TextField(blank=True, null=True),
        ),
    ]
